development:
  access_key_id:"AKIAIPJZD3CRMZ5CS6TA"
  secret_access_key:"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"
  bucket:"thesea"

test:
  access_key_id:"AKIAIPJZD3CRMZ5CS6TA"
  secret_access_key:"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"
  bucket:"thesea"

production:
  access_key_id:"AKIAIPJZD3CRMZ5CS6TA"
  secret_access_key:"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"
  bucket:"thesea"
