app_key: "a4mupugbluh6xfq"
app_secret: "lqhmm37sutqdnyi"
access_token: "ftCZDgksAkUAAAAAAAAPqQAN7aXcDC6PwiuaW96ldbzwTJH91LpVDMw-yRUlvFes"
user_id: "alex.burton1993@gmail.com"
access_type: "dropbox|app_folder"
